#!/usr/bin/env python3
"""FASB ASC Topic 注册表（用于 Codification 导出）。"""

from __future__ import annotations

# (num, name_en, name_cn, key)
ASC_TOPICS: list[tuple[int, str, str, bool]] = [
    (105, "Generally Accepted Accounting Principles", "公认会计原则", False),
    (205, "Presentation of Financial Statements", "财务报表列报", False),
    (210, "Balance Sheet", "资产负债表", False),
    (220, "Income Statement—Reporting Comprehensive Income", "综合收益", False),
    (225, "Income Statement", "利润表", False),
    (230, "Statement of Cash Flows", "现金流量表", False),
    (235, "Notes to Financial Statements", "财务报表附注", False),
    (250, "Accounting Changes and Error Corrections", "会计变更与差错更正", False),
    (255, "Changing Prices", "物价变动", False),
    (260, "Earnings Per Share", "每股收益", False),
    (270, "Interim Reporting", "中期报告", False),
    (272, "Limited Liability Entities", "有限责任主体", False),
    (274, "Personal Financial Statements", "个人财务报表", False),
    (275, "Risks and Uncertainties", "风险与不确定性", False),
    (280, "Segment Reporting", "分部报告", False),
    (310, "Receivables", "应收款项", False),
    (320, "Investments—Debt and Equity Securities", "债务与权益证券投资", False),
    (321, "Investments—Equity Securities", "权益证券投资", False),
    (323, "Investments—Equity Method and Joint Ventures", "权益法与合营", False),
    (325, "Investments—Other", "其他投资", False),
    (326, "Financial Instruments—Credit Losses", "金融工具—信用损失", True),
    (330, "Inventory", "存货", False),
    (340, "Other Assets and Deferred Costs", "其他资产与递延成本", False),
    (350, "Intangibles—Goodwill and Other", "无形资产与商誉", True),
    (360, "Property Plant and Equipment", "不动产、厂房和设备", True),
    (405, "Liabilities", "负债", False),
    (410, "Asset Retirement and Environmental Obligations", "资产退役与环境义务", False),
    (420, "Exit or Disposal Cost Obligations", "退出与处置成本", False),
    (430, "Deferred Revenue", "递延收入", False),
    (440, "Commitments", "承诺事项", False),
    (450, "Contingencies", "或有事项", True),
    (460, "Guarantees", "担保", False),
    (470, "Debt", "债务", False),
    (480, "Distinguishing Liabilities From Equity", "负债与权益区分", False),
    (505, "Equity", "权益", False),
    (605, "Revenue Recognition", "收入确认（旧）", False),
    (606, "Revenue From Contracts With Customers", "客户合同收入", True),
    (610, "Other Income", "其他收入", False),
    (710, "Compensation—General", "雇员报酬—一般", False),
    (712, "Compensation—Nonretirement Postemployment Benefits", "雇员报酬—离职后", False),
    (715, "Compensation—Retirement Benefits", "雇员退休福利", True),
    (718, "Compensation—Stock Compensation", "股份支付", True),
    (720, "Other Expenses", "其他费用", False),
    (730, "Research and Development", "研究与开发", False),
    (740, "Income Taxes", "所得税", True),
    (805, "Business Combinations", "企业合并", True),
    (808, "Collaborative Arrangements", "协作安排", False),
    (810, "Consolidation", "合并报表", True),
    (815, "Derivatives and Hedging", "衍生工具与套期", True),
    (820, "Fair Value Measurement", "公允价值计量", True),
    (825, "Financial Instruments", "金融工具", True),
    (830, "Foreign Currency Matters", "外币事项", False),
    (835, "Interest", "利息", False),
    (842, "Leases", "租赁", True),
    (848, "Reference Rate Reform", "参考利率改革", False),
    (850, "Related Party Disclosures", "关联方披露", False),
    (855, "Subsequent Events", "期后事项", False),
    (860, "Transfers and Servicing", "转移与服务", False),
    (905, "Agriculture", "农业", False),
    (908, "Airlines", "航空", False),
    (910, "Contractors—Construction", "建筑承包商", False),
    (912, "Contractors—Federal Government", "联邦政府承包商", False),
    (915, "Development Stage Entities", "发展阶段主体", False),
    (920, "Entertainment—Broadcasters", "娱乐—广播", False),
    (922, "Entertainment—Cable Television", "娱乐—有线电视", False),
    (924, "Entertainment—Casinos", "娱乐—赌场", False),
    (926, "Entertainment—Films", "娱乐—电影", False),
    (928, "Entertainment—Music", "娱乐—音乐", False),
    (930, "Extractive Activities—Mining", "采矿业", False),
    (932, "Extractive Activities—Oil and Gas", "油气开采", False),
    (940, "Financial Services—Brokers and Dealers", "金融服务—经纪商", False),
    (942, "Financial Services—Depository and Lending", "金融服务—存款与贷款", False),
    (944, "Financial Services—Insurance", "保险", True),
    (946, "Financial Services—Investment Companies", "金融服务—投资公司", False),
    (948, "Financial Services—Mortgage Banking", "金融服务—按揭银行", False),
    (950, "Financial Services—Title Plant", "金融服务—产权档案", False),
    (952, "Franchisors", "特许加盟商", False),
    (954, "Health Care Entities", "医疗保健主体", False),
    (958, "Not-for-Profit Entities", "非营利主体", False),
    (960, "Plan Accounting—Defined Benefit Pension Plans", "计划会计—设定受益", False),
    (962, "Plan Accounting—Defined Contribution Pension Plans", "计划会计—设定提存", False),
    (965, "Plan Accounting—Health and Welfare Benefit Plans", "计划会计—健康福利", False),
    (970, "Real Estate—General", "房地产—一般", False),
    (972, "Real Estate—Common Interest Realty Associations", "房地产—共益实体", False),
    (974, "Real Estate—Real Estate Investment Trusts", "房地产—REITs", False),
    (978, "Real Estate—Time-Sharing Activities", "房地产—分时度假", False),
    (980, "Regulated Operations", "受管制业务", False),
    (985, "Software", "软件", False),
]

TOPIC_MAP: dict[int, tuple[str, str, bool]] = {
    num: (en, cn, key) for num, en, cn, key in ASC_TOPICS
}
